### ISSUE TITLE
Reading Hot Water

### ISSUE THREAD

**Issue by benneaves** [dehsgr/node-red-contrib-evohome#4] opened 2019-09-26 06:59 UTC
At the moment only heating zones are reported, hot water values are not broadcast
On other EvoHome API decoders i have seen, hotwater appears in an unnamed zone. 
Seems to work ok in this code
https://gist.github.com/davesarg/a453915074c5508dda8a

**Comment by dehsgr** [comment] 2019-09-26 07:08
As I don't have any Evohome myself I'm currently not able to implement this. Feel free to (find one to) contribute.

**Comment by benneaves** [comment] 2019-09-26 07:24
looks like the code to implement is already there, ill make some tweeks to see if it works

if(locations[0].devices[deviceId].zoneID == thermostats[thermoId].zoneId) {
                                        if(locations[0].devices[deviceId].name  == "") {
                                            // Device name is empty
                                            // Probably Hot Water
                                            // Do not store
                                            console.log("Found blank device name, probably stored hot water. Ignoring device for now.");
                                        } else {
                                            var msgout = {
                                                payload : {
                                                    id: thermostats[thermoId].zoneId,
                                                    name : locations[0].devices[deviceId].name.toLowerCase(),
                                                    currentTemperature : thermostats[thermoId].temperatureStatus.temperature,
                                                    targetTemperature : thermostats[thermoId].setpointStatus.targetHeatTemperature
                                                }

**Comment by Dharma1966** [comment] 2019-10-17 13:49
Hi, I'm creating an automation for my heating. I configured the node node-red-contrib-evohome. The problem is that sometimes the system does not connect to the sever giving this error: "TypeError: Cannot read property 'locationId' of undefined". Restarting the Add-ons by Hass.io Node-RED, the error disappears until it reappears after a few calls.Chiaramennte so the automation is not usable ... do you have any advice?

**Comment by davies8172** [comment] 2020-06-21 09:08
Did anyone get anywhere with this fix? I would love to bring in hot water temperature into my dashboard if available?

**Comment by tstaddon** [comment] 2021-02-02 01:54
I did find some stuff on the Automated Home forum but don't have HW to test the code:

[Automatedhome.co.uk](https://www.automatedhome.co.uk/vbulletin/showthread.php?3863-Decoded-EvoHome-API-access-to-control-remotely&p=41119&viewfull=1#post41119)

@dehsgr - I don't know if it's relevant but some of the authentication code in andremain's SmartThings project has been updated very recently and could be worth a collaboration:

[github.com/andremain/EvohomeSmartthings2020](
https://github.com/andremain/EvohomeSmartthings2020/blob/main/Evohome%20Connect%202020%20smartApp%20Release1.8.txt)

**Comment by dehsgr** [comment] 2021-02-02 05:21
@tstaddon thanks for this hint. I‘ll take a look when there is some time. Currently I‘m busy and I‘ve no Evohome for testing.

**Comment by dehsgr** [comment] 2022-10-12 07:04
No time for implementation and no platform for testing those changes here. Feel free to contribute. I'll close this now.

**Closed as completed by dehsgr** 2022-10-12 07:04 UTC
Labels: enhancement
